### ISSUE TITLE
Use NextJS for better web performance 

### ISSUE THREAD

**Issue by RakeshSangem** [blossomlabsio/bloom#15]
React docs itself suggesting to use frameworks so `NextJS` would be great for this project.

Why NextJS?

- SEO friendly
- server side rendering
- file based router helps in developing
- static site generation

And more...

**Comment by ShreyaPrasad1209** [comment]
@RakeshSangem while I agree with your points, Bloom is a CFP management tool which means it involves:

- Lots of dynamic content generation
- User interaction

For above cases, SSR actually slows down because it'll take time to fetch the compiled JS files from server and render an empty HTML page which is bad UX. If it were a static site, then Next.js would be perfect. I hope that answers your question. 😃

**Comment by ShreyaPrasad1209** [comment]
@RakeshSangem I'm assuming you have no further questions so I'm closing this issue. In the future, you can raise your questions in Discussions. Have a great day ahead  🙌🏻
